services:
  - type: web
    name: seed-of-life-registration
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run backend
    envVars:
      - key: NODE_VERSION
        value: 24.13.1
